version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: "postgresql://postgres:docker@db:5432/db?schema=public"
      PORT: 3000
      API_KEY: "adaptive"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  app_prod:
    build:
      context: .
      target: production
    environment:
      DATABASE_URL: "postgresql://postgres:docker@db:5432/db?schema=public"
      PORT: 8080
      API_KEY: "adaptive"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
